<?php

/**
 * Implements hook_theme().
 */
function dovelewis_found_pets_theme($existing, $type, $theme, $path) {
  return [
    // Blocks.
    'block__found_pet_claim' => [
      'template' => 'block--found-pet-claim',
      'base hook' => 'block',
      'path' => $path . '/templates/blocks',
    ],
    'block__found_pet_microchips' => [
      'template' => 'block--found-pet-microchips',
      'base hook' => 'block',
      'path' => $path . '/templates/blocks',
    ],
    // Fields.
    'field__node__field_found_near__lost_found_pet__full' => [
      'template' => 'field--node--field-found-near--lost-found-pet--full',
      'base hook' => 'field',
      'path' => $path . '/templates/fields',
    ],
    // Nodes.
    'node__lost_found_pet__full' => [
      'template' => 'node--lost-found-pet--full',
      'base hook' => 'node',
      'path' => $path . '/templates/nodes',
    ],
    'node__lost_found_pet__teaser' => [
      'template' => 'node--lost-found-pet--teaser',
      'base hook' => 'node',
      'path' => $path . '/templates/nodes',
    ],
    // Views.
    'views_view__found_pets__teaser_block' => [
      'template' => 'views-view--found-pets--teaser-block',
      'base hook' => 'views_view',
      'path' => $path . '/templates/views',
    ],
    'views_view_unformatted__found_pets__landing_block' => [
      'template' => 'views-view-unformatted--found-pets--landing-block',
      'base hook' => 'views_view_unformatted',
      'path' => $path . '/templates/views',
    ],
  ];
}

/**
 * Implements hook_preprocess_block().
 *
 * Preprocess block.html.twig.
 */
function dovelewis_found_pets_preprocess_block(&$vars) {

  if (!empty($vars['attributes']['id'])) {

    switch($vars['attributes']['id']) {

      // "Claim your pet" block.
      case 'block-found-pet-claim':

        // Disable cache for this block because we need
        // to insert the tracking number that we retrieve
        // from the current node.
        unset($vars['elements']['#cache']);
        unset($vars['#cache']);
        unset($vars['content']['#cache']);
        $vars['#cache'] = [];
        $vars['#cache']['max-age'] = 0;

        // Retrieve value of field_tracking_number to render in block template.
        $node = \Drupal::routeMatch()->getParameter('node');
        if ($node) {
          if ($node->hasField('field_tracking_number')) {
            $vars['tracking_number'] = $node->get('field_tracking_number')
              ->getValue()[0]['value'];
          }
        }

        break;
    }
  }
}

/**
 * Implements hook_preprocess_template().
 *
 * Preprocess field--node--field-found-near--lost-found-pet--full.html.twig.
 */
function dovelewis_found_pets_preprocess_field__node__field_found_near__lost_found_pet__full(&$vars) {
  $field_value = $vars['items'][0]['content']['#context']['value'];
  if (!empty($field_value)) {
    // URL encode address argument for Google Maps API.
    $field_value = urlencode($field_value);
    $vars['google_maps_arg'] = $field_value;
  }
}
