<?php


/**
 * Implements hook_form_alter().
 */
function dovelewis_contact_form_alter(&$form, $form_state, $form_id) {
  // Hide preview button of contact form.
  // Change submit button text.
  if ($form_id == 'contact_message_feedback_form') {
    $form['actions']['preview']['#access'] = FALSE;

    $form['actions']['submit']['#value'] = t('Send Feedback');
  }
}


/**
 * Implements hook_mail_alter().
 */
function dovelewis_contact_mail_alter(&$message) {

  if ($message['id'] == 'contact_page_mail') {
    // Change recipient based on value of subject field.
    $chosen_department = $message['params']['contact_message']->getFields()['field_subject']->getValue()[0]['value'];

    switch ($chosen_department) {
      // 'Management'.
      case '0':
        $recipient = 'contact@dovelewis.org';

        break;

      // 'Blood Bank'.
      case '1':
        $recipient = 'bloodbank@dovelewis.org';

        break;

      // 'Pet Loss Support Program'.
      case '2':
        $recipient = 'ralexander@dovelewis.org';

        break;

      // 'Portland Area Canine Therapy Teams (PACTT)'.
      case '3':
        $recipient = 'kloter@dovelewis.org';

        break;

      // 'Donations + Support'.
      case '4':
        $recipient = 'development@dovelewis.org';

        break;

      // 'Volunteering'.
      case '5':
        $recipient = 'volunteer@dovelewis.org';

        break;

      // 'Marketing & Media'.
      case '6':
        $recipient = 'contact@dovelewis.org';

        break;
    }

    if (isset($recipient)) {
      $message['to'] = $recipient;
    }
  }
}
